# mqtt-exporter/config.yml
mqtt:
  server: tcp://mosquitto:1883
  user: ""
  password: ""
  topic_path: pico/env

cache:
  timeout: 120s

json_parsing:
  separator: .

metrics:
  - prom_name: pico_co2
    mqtt_name: co2
    help: "CO2 concentration"
    type: gauge

  - prom_name: pico_lux
    mqtt_name: lux
    help: "Light level"
    type: gauge

  - prom_name: pico_temp
    mqtt_name: temp
    help: "Temperature in Celsius"
    type: gauge

  - prom_name: pico_hum
    mqtt_name: hum
    help: "Relative Humidity in percent"
    type: gauge