# prometheus.yml
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "mqtt-exporter"
    static_configs:
      - targets: ["mqtt-exporter:9641"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
