services:
  # --- FRONTEND ---
  frontend:
    container_name: react_app
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - monitoring
    depends_on:
      - fastapi
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  # --- BACKEND (FastAPI) ---
  fastapi:
    container_name: fastapi_app
    build: ./backend/postgress-websocket 
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitoring

  # --- DATABASE ---
  postgres:
    container_name: pico_metrics
    image: postgres:latest
    
    volumes:
      - postgres_data:/var/lib/postgresql 
    ports:
      - "54827:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  # --- MQTT & INFRASTRUCTURE ---
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"  
    volumes:
      - ./backend/mosquitto/config:/mosquitto/config
    networks:
      - monitoring

  mqtt-exporter:
    image: hikhvar/mqtt2prometheus:latest
    container_name: mqtt-exporter
    command: ["-config", "/config.yml"]
    volumes:
      - ./backend/mqtt-exporter/config.yml:/config.yml
    ports:
      - "9641:9641"
    depends_on:
      - mosquitto
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./backend/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9091:9090"
    networks:
      - monitoring

  notifier:
    build: ./backend/notifier
    image: am106ac/notifier:latest
    container_name: notifier
    restart: unless-stopped
    environment:
      - NOTIFIER_BROKER=mosquitto
      - NOTIFIER_PORT=1883
      - NOTIFIER_BASE_TOPIC=pico/env
      - NOTIFIER_APPRISE_URL=${NOTIFIER_APPRISE_URL}
    depends_on:
      - mosquitto
    healthcheck:
      test: ["CMD", "python3", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  postgres_data: